version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: myapi_laravel-app
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    ports:
      - "8000:8000"

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: pam123
      MYSQL_DATABASE: laravel
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
